LIME-565: Adding activity history score and associated checks to the VC
alphagov/di-ipv-cri-fraud-api pull request #172
Opened 2023-06-07 08:19 UTC by gds-jbentham

## Proposed changes

### What changed

Added activity history score to the VC
Added empty check to the VC for activity from
```
				{
					"checkMethod": "data",
					"activityFrom": "2019-01-01",
					"identityCheckPolicy": "none"
				}
```
Updated tests
Added new acceptance tests

### Why did it change

So that we could return activity history score while still adhering to RFC 24

2023-06-07 09:10 UTC, Wynndow commented
Hey @gds-jbentham - I'm looking at the core side of this - how we handle the new activity score on a fraud VC. Is it going to be possible for the fraud CRI to return a VC containing a CI as well as a non-zero activity score?

2023-06-07 09:30 UTC, gds-jbentham commented
Hi @Wynndow 
Yeah that would be possible as we could get an Experian ucode indicating a CI is required. But if the user had record with a defined date in the response we would still calculate the activity history score

2023-06-08 15:41 UTC, smsgds submitted a review, later dismissed

2023-06-13 12:24 UTC, smsgds commented
> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=BUG) [![B](https://camo.githubusercontent.com/ee7f8cac547e3e28ad7e683c451c8caf2f19d70bc37d6bcba574dac8ff86d194/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f422d313670782e706e67)](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=BUG) [2 Bugs](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=CODE_SMELL) [10 Code Smells](https://sonarcloud.io/project/issues?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&resolved=false&types=CODE_SMELL)
> 
> [![0.0%](https://camo.githubusercontent.com/3f04cff3eeef8477afe696ae55c570cbb6ed02f16152497c14251828329a3e91/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302d313670782e706e67)](https://sonarcloud.io/component_measures?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=alphagov_di-ipv-cri-fraud-api&pullRequest=172&metric=new_duplicated_lines_density&view=list)


The asserts being in the wrong order will be confusing to read if they fail

2023-06-13 12:25 UTC, smsgds requested changes
Unit test asserts are swapped

2023-06-13 16:16 UTC, smsgds approved these changes

2023-06-13 16:17 UTC, gds-jbentham commented on lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/item/FraudResultItem.java
>      private Integer activityHistoryScore;
I thought that but it also means I cant exclude it by setting it to null

2023-06-14 11:09 UTC, merged

2023-06-14 11:11 UTC, smsgds commented on lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/persistence/item/FraudResultItem.java
>      private Integer activityHistoryScore;
Depends on if activityHistoryScore is always going to be done going forward, if not then this way is best so it can be excluded early.