LIME-234 Use only the current address in pep requests
alphagov/di-ipv-cri-fraud-api pull request #87
Opened 2022-10-20 16:06 UTC by smsgds

## Proposed changes

### What changed

PEP check changed to use only the current address in requests.

### Why did it change

Third-party API does not support multiple addresses for PEP checks.

### Issue tracking

- [LIME-234](https://govukverify.atlassian.net/browse/LIME-234)

2022-10-21 10:52 UTC, tal-nagra requested changes

2022-10-21 10:52 UTC, tal-nagra commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
>      final String tenantId;
add the `private` access modifier here

2022-10-21 10:52 UTC, tal-nagra commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +    List<Address> mapFraudCheckMultipleAddresses(
The name can remain as `mapAddresses` as the name and the return type imply that multiple addresses will be returned by this method. 
Add the `private` access modifier

2022-10-21 10:52 UTC, tal-nagra commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +                    Address address = createAddressFromPersonAddress(addressId, personAddress);
A more succinct syntax could be used here such as:
return personAddresses.stream()
                .map(personAddress -> createAddressFromPersonAddress(addressId.incrementAndGet(), personAddress))
                .collect(Collectors.toList())

2022-10-21 10:52 UTC, tal-nagra commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +    List<Address> mapPEPCheckSingleCurrentAddress(
Change the return type to just Address here as this method is intended to return a single address

Add the `private` access modifier to all appropriate methods in this class

2022-10-21 10:52 UTC, tal-nagra commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +                        Address address = createAddressFromPersonAddress(addressId, personAddress);
you can use a stream().filter( ... ).map( ... ).collect(Collectors.toList()) here too

2022-10-21 10:52 UTC, tal-nagra commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +        return addresses;
return the first element in the list rather than the entire list

2022-10-21 10:52 UTC, tal-nagra commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +    private Address createAddressFromPersonAddress(
rename this method to mapAddress so that it follows the naming convention used elsewhere in this file

2022-10-21 11:07 UTC, ElliotMurphyGDS commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +    List<Address> mapFraudCheckMultipleAddresses(
For clarity, to avoid future confusion and to be inline with the other pepAddress mapping method can we change the method name to "mapMultipleAddresses"

2022-10-21 12:35 UTC, smsgds commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
>      final String tenantId;
This is not related to the fix, but I agree tenantId should have been private

2022-10-21 12:36 UTC, smsgds commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +    List<Address> mapFraudCheckMultipleAddresses(
mapMultipleAddresses is now called in fraud request creation and mapSingleAddress for PEP

2022-10-21 12:38 UTC, smsgds commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +                    Address address = createAddressFromPersonAddress(addressId, personAddress);
In fraud we already have excessive use of the stream API when processing small lists, I want to avoid adding more. These lists for most users will be for 1 address.

2022-10-21 12:40 UTC, smsgds commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +    private Address createAddressFromPersonAddress(
Agreed map better describes what this method is doing

2022-10-21 12:46 UTC, smsgds commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/gateway/IdentityVerificationRequestMapper.java
> +        return addresses;
For mapSingleAddres, the error message is to ensure that if the requirement is added to the system to support multiple current addresses, that pep does not start silently failing again due to that.
Right now the rest of fraudCRI can support this, but the PEP requests requires a single address only. As this is recent issue there not enough information or direction on which current address we would use in a situation of choosing between current addresses.

2022-10-25 12:48 UTC, ElliotMurphyGDS approved these changes

2022-10-25 13:55 UTC, merged